name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-twisted python3-nose
        python -m pip install --upgrade pip
        pip install prego3
        python3 --version
    - name: Test with prego
      run: |
        pypath=$(pip3 show -f PyHamcrest | grep ^Location | awk '{print $2}')
        export PYTHONPATH=$pypath
        # echo pyhamcrest location: $pypath
        # echo site --user-site
        # python3 -m site --user-site
        # python3 -c 'import site; print("- getsitepackages: {}\n- getusersitepackages: {}\n- USER_BASE {}\n--".format(site.getsitepackages(), site.getusersitepackages(), site.USER_BASE))'       
        nosetests3 -v -s test/test.py
